name: favorite_idol
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  image_picker: ^1.1.2
  timeago: ^3.7.0
  image: ^4.5.2
  path_provider: ^2.1.5
  http: ^1.2.2
  shared_preferences: ^2.3.5
  crypto: ^3.0.6

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  kakao_flutter_sdk: ^1.9.6

  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
