// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3AAgfYWLvS0g8qdO42xQrXDklhIJCkXo',
    appId: '1:462331059744:web:0dde7ea74e2f4579e96645',
    messagingSenderId: '462331059744',
    projectId: 'favorite-idol',
    authDomain: 'favorite-idol.firebaseapp.com',
    storageBucket: 'favorite-idol.firebasestorage.app',
    measurementId: 'G-61XNE50SNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwwobGA_9usQFIZZFbmK1c7daDb0KP3HY',
    appId: '1:462331059744:android:29786e7f2dbb74d2e96645',
    messagingSenderId: '462331059744',
    projectId: 'favorite-idol',
    storageBucket: 'favorite-idol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPrnAwf8SeI4RgrZF5d3jT17i9aL9NBOY',
    appId: '1:462331059744:ios:5654e7b21b042351e96645',
    messagingSenderId: '462331059744',
    projectId: 'favorite-idol',
    storageBucket: 'favorite-idol.firebasestorage.app',
    iosBundleId: 'com.example.favoriteIdol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPrnAwf8SeI4RgrZF5d3jT17i9aL9NBOY',
    appId: '1:462331059744:ios:5654e7b21b042351e96645',
    messagingSenderId: '462331059744',
    projectId: 'favorite-idol',
    storageBucket: 'favorite-idol.firebasestorage.app',
    iosBundleId: 'com.example.favoriteIdol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3AAgfYWLvS0g8qdO42xQrXDklhIJCkXo',
    appId: '1:462331059744:web:69f5eb89064ec13ae96645',
    messagingSenderId: '462331059744',
    projectId: 'favorite-idol',
    authDomain: 'favorite-idol.firebaseapp.com',
    storageBucket: 'favorite-idol.firebasestorage.app',
    measurementId: 'G-XYERZWSBCL',
  );
}
